### ISSUE TITLE
Doesn't work on latest version of the game

### ISSUE THREAD

**Issue by IceloveandlifeAJ** [UnityPluginManager/SlimeRancher.DebugMenu#6]
I don't know if it's just me or what, but it seems quite a few of the mod's features aren't working with the newest version of Slime Rancher. I know last time I looked noclip, add/remove money, infinite health and energy, and randomized inventory were/are all features that weren't working.

**Comment by DaZombieKiller** [comment]
Known issue, I recently completely rewrote the debug menu, along with starting work on a completely new iteration of UPM (available [here](https://github.com/GamePluginKit/GamePluginKit), but there aren't any prebuilt binaries since it's still a WIP).

The improved version should be coming out sometime soon, I just need to do some more testing, write the documentation on setting it up, and make sure everything works together smoothly and isn't overly complicated.
